PROMPT = """\
[lexical]
Use when the core discussion is about shared wording, word substitution, particles,
or close-form verbal variation across compared verses.

Valid hints for `similarity_type`:
- exact_verbal_match
- partial_verbal_match
- root_match
- particle_variation
- morphology_variation

Arabic guidance:
- `shared_segment.text` should contain the exact shared Arabic phrase.
- `differences` should capture concrete word-level differences, not thematic summaries.
- If a wording difference is driven by syntactic position (i'rab, taqdim/ta'khir, governing particles),
  classify as structural instead of lexical.

Example `category_payload`:
{
  "type": "lexical",
  "similarity_type": "partial_verbal_match",
  "shared_segment": {"text": "ألم أقل", "word_count": 2},
  "differences": [
    {
      "position": "middle phrase",
      "in_primary": "تستطع",
      "in_related": "تستطيع",
      "difference_type": "addition",
      "roots_primary": ["طوع"],
      "roots_related": ["طوع"],
      "same_root": true,
      "morphological_note": "زيادة ياء في الصيغة"
    }
  ],
  "confusion_level": "medium",
  "confusion_note_ar": "التشابه لفظي مع فرق صرفي يسير",
  "confusion_note_en": "Mostly lexical overlap with minor morphology difference",
  "scholarly_explanation_ar": "الزيادة هنا للتأكيد بعد تكرر الموقف",
  "scholarly_explanation_en": "The addition increases emphasis after repeated context",
  "mnemonic_hint": "ابحث عن الزيادة في موضع العتاب الثاني",
  "mnemonic_hint_source": "llm_generated"
}

Source attribution rule:
- If mnemonic_hint is generated by reasoning (not explicitly in source text), set
  `mnemonic_hint_source` to "llm_generated".
- Use "extracted" only when the source author explicitly provides a memorization cue.
- If system prompt says the book has no mnemonic content, leave `mnemonic_hint` null.

Hallucination guard:
- Do not invent mnemonic devices or pedagogical tricks absent from source text.

Category confidence anchors (lexical):
- 0.90: exact or near-exact phrase overlap + explicit source-grounded explanation of the lexical difference.
- 0.60: lexical overlap is clear but rationale is partially inferred.
- 0.35: overlap is weak/indirect or might be better classified as structural/semantic.
"""

